# Generated by Django 6.0.3 on 2026-03-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('vibe', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('highlight', models.CharField(max_length=140)),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('detail', models.TextField()),
                ('duration', models.CharField(max_length=60)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='travelogue.destination')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
